// vue3-pinia/src/views/CarDetails/widgets/CarDetails/CarDetailsWidget.vue
<script lang="ts" setup>
const props = defineProps<{ id: string }>();

type CarDetails = {
  id: number;
  model: string;
  brand: string;
  year: number;
};

const carDetails = await fetch(`http://localhost:3001/cars/${props.id}`).then(
  (res) => res.json() as unknown as CarDetails
);
</script>

<template>
  <div class="card w-96 shadow-xl">
    <div class="card-body">
      <h2 class="card-title">Car details</h2>
      <table class="table w-full">
        <tbody>
          <tr>
            <td><b>Brand</b></td>
            <td>{{ carDetails.brand }}</td>
          </tr>
          <tr>
            <td><b>Model</b></td>
            <td>{{ carDetails.model }}</td>
          </tr>
          <tr>
            <td><b>Year</b></td>
            <td>{{ carDetails.year }}</td>
          </tr>
        </tbody>
      </table>
      <div class="card-actions justify-end">
        <RouterLink class="btn mr-2" to="/">Back</RouterLink>
      </div>
    </div>
  </div>
</template>

// next-beta/app/cars/[id]/widgets/CarDetails/CarDetails.widget.tsx
import {CarDetails} from "./CarDetails.types";
import {EditCarButton} from "../../../../../widgets/EditCarButton/EditCarButton";
import Link from "next/link";

async function getData(id: string): Promise<CarDetails> {
    const res = await fetch(`http://localhost:3001/cars/${id}`, {next: {revalidate: 1}})

    return res.json();
}

export default async function CarDetailsWidget({id}: { id: string }) {
    const carDetails = await getData(id);

    return (
        <div className="card w-96 bg-base-100 shadow-xl">
            <div className="card-body">
                <h2 className="card-title">Car details</h2>
                <table className="table w-full">
                    <tbody>
                    <tr>
                        <td><b>Brand</b></td>
                        <td>{carDetails.brand}</td>
                    </tr>
                    <tr>
                        <td><b>Model</b></td>
                        <td>{carDetails.model}</td>
                    </tr>
                    <tr>
                        <td><b>Year</b></td>
                        <td>{carDetails.year}</td>
                    </tr>
                    </tbody>
                </table>
                <div className="card-actions justify-end">
                    <Link href="/" className="btn mr-2">Back</Link>
                    <EditCarButton id={id}/>
                </div>
            </div>
        </div>

    )
}
