// vue3-pinia/src/views/CarList/widgets/CarList/components/CarListRow.vue
<script lang="ts" setup>
import ShowEditCarDialogButtonWidget from "@/views/CarList/widgets/ShowEditCarDialogButton/ShowEditCarDialogButtonWidget.vue";

type CarListItem = {
  id: number;
  model: string;
  brand: string;
  year: number;
};

defineProps<{ car: CarListItem }>();
</script>

<template>
  <tr>
    <th>{{ car.id }}</th>
    <td>{{ car.brand }}</td>
    <td>{{ car.model }}</td>
    <td>{{ car.year }}</td>
    <td>
      <ShowEditCarDialogButtonWidget :id="car.id" class="mr-3" />
      <RouterLink :to="{ name: 'CarDetails', params: { id: car.id } }"
        >View
      </RouterLink>
    </td>
  </tr>
</template>

// next-beta/app/widgets/CarList/components/CarListRow.tsx
import Link from "next/link";
import {CarListItem} from "../CarList.types";
import {EditCarButton} from "../../../../widgets/EditCarButton/EditCarButton";

export default function CarListRow({car}: { car: CarListItem }) {
    return (<tr key={car.id}>
        <th>{car.id}</th>
        <td>{car.brand}</td>
        <td>{car.model}</td>
        <td>{car.year}</td>
        <td>
            <EditCarButton id={`${car.id}`}/>
            <Link href={`/cars/${car.id}`}>View</Link>
        </td>
    </tr>)
}
