// next-beta/app/widgets/CreateCarDialog/CreateCarDialog.widget.tsx
'use client'

import {CreateCarConfirmationDialog} from "./components/CreateCarConfirmationDialog";
import {EditCarDialogErrorBoundary} from "../../../widgets/EditCarDialog/components/EditCarDialogErrorBoundary";
import {CreateCarDialogContent} from "./components/CreateCarDialogContent";
import {useCreateCarDialogUI} from "./hooks/useCreateCarDialogUI";

const useCreateCarDialogState = () => {

    const {isCreateCarDialogOpen, onCreateCarDialogCloseHandler} = useCreateCarDialogUI()

    return {
        isOpen: isCreateCarDialogOpen,
        onCloseHandler: onCreateCarDialogCloseHandler
    } as const;
}


export const CreateCarDialogWidget = () => {
    const {isOpen, onCloseHandler} = useCreateCarDialogState();

    if(!isOpen) return null;

    return (
        <div className="modal modal-open">
            <div className="modal-box relative">
                <label className="btn btn-sm btn-circle absolute right-2 top-2" onClick={onCloseHandler}>✕</label>
                <h3 className="font-bold text-lg mb-5">Edit car</h3>
                <EditCarDialogErrorBoundary>
                    <CreateCarDialogContent/>
                </EditCarDialogErrorBoundary>
            </div>
            <CreateCarConfirmationDialog/>
        </div>
    )
}

// vue3-pinia/src/views/CarList/widgets/CreateCarDialog/CreateCarDialogWidget.vue
<script lang="ts" setup>
import { useCreateCarDialogUI } from "@/views/CarList/widgets/CreateCarDialog/store/useCreateCarDialogUI";
import CreateCarDialogContent from "@/views/CarList/widgets/CreateCarDialog/components/CreateCarDialogContent.vue";
import CreateCarConfirmationDialog from "@/views/CarList/widgets/CreateCarDialog/components/CreateCarConfirmationDialog.vue";

const createCarDialogUI = useCreateCarDialogUI();
</script>

<template>
  <div
    :class="[
      'modal',
      { 'modal-open': createCarDialogUI.isCreateCarDialogOpen },
    ]"
  >
    <div class="modal-box relative">
      <label
        class="btn btn-sm btn-circle absolute right-2 top-2"
        @click="createCarDialogUI.closeCreateCarDialog"
        >✕</label
      >
      <h3 class="font-bold text-lg mb-5">Create car</h3>
      <CreateCarDialogContent />
    </div>
  </div>
  <CreateCarConfirmationDialog />
</template>
