// next-beta/widgets/EditCarDialog/EditCarDialogWidget.tsx
'use client'

import {Suspense} from "react";
import {EditCarConfirmationDialog} from "./components/EditCarConfirmationDialog";
import {useEditCarDialogUI} from "./hooks/useEditCarDialogUI";
import {EditCarDialogContent} from "./components/EditCarDialogContent";
import {EditCarDialogLoadingPlaceholder} from "./components/EditCarDialogLoadingPlaceholder";
import {EditCarDialogErrorBoundary} from "./components/EditCarDialogErrorBoundary";
import {EditCarDialogError} from "./components/EditCarDialogError";

export default function EditCarDialogWidget({id}: { id: string }) {

    const {closeEditCarDialog, isEditCarDialogOpen} = useEditCarDialogUI({id});

    if (!isEditCarDialogOpen) return null;

    return (
        <div className="modal modal-open">
            <div className="modal-box relative">
                <label className="btn btn-sm btn-circle absolute right-2 top-2" onClick={closeEditCarDialog}>✕</label>
                <h3 className="font-bold text-lg mb-5">Edit car</h3>
                <EditCarDialogErrorBoundary>
                    <Suspense fallback={<EditCarDialogLoadingPlaceholder/>}>
                        <EditCarDialogContent/>
                    </Suspense>
                </EditCarDialogErrorBoundary>
            </div>
            <EditCarConfirmationDialog/>
            <EditCarDialogError/>
        </div>
    )
}

// vue3-pinia/src/views/CarList/widgets/EditCarDialog/EditCarDialogWidget.vue
<script setup lang="ts">
import { useEditCarDialogUI } from "@/views/CarList/widgets/EditCarDialog/store/useEditCarDialogUI";
import EditCarDialogContent from "@/views/CarList/widgets/EditCarDialog/componenets/EditCarDialogContent.vue";
import EditCarConfirmationDialog from "@/views/CarList/widgets/EditCarDialog/componenets/EditCarConfirmationDialog.vue";

const editCarDialogUI = useEditCarDialogUI();
</script>
<template>
  <div :class="['modal', { 'modal-open': editCarDialogUI.isOpen }]">
    <div class="modal-box relative">
      <label
        class="btn btn-sm btn-circle absolute right-2 top-2"
        @click="editCarDialogUI.close"
        >✕</label
      >
      <h3 class="font-bold text-lg mb-5">Edit car</h3>
      <Suspense
        v-if="editCarDialogUI.editCarId"
        :key="editCarDialogUI.editCarId"
      >
        <EditCarDialogContent :id="editCarDialogUI.editCarId" />
        <template #fallback> ...loading </template>
      </Suspense>
    </div>
  </div>
  <EditCarConfirmationDialog />
</template>
