// next-beta/widgets/EditCarDialog/components/EditCarConfirmationDialog.tsx
'use client'

import {useEditCarConfirmationDialogUI} from "../hooks/useEditCarConfirmationDialogUI";

export const EditCarConfirmationDialog = () => {
    const {
        onConfirmationDialogConfirmHandler,
        onConfirmationDialogCancelHandler,
        isConfirmationDialogOpen
    } = useEditCarConfirmationDialogUI();

    if (!isConfirmationDialogOpen) return null

    return (
        <div className="modal modal-open">
            <div className="modal-box relative">
                <h3 className="font-bold text-lg mb-5">Edit car</h3>
                <p className="py-4">Form contains unsaved data. Please confirm action.</p>
                <div className="modal-action">
                    <button className="btn btn-secondary" onClick={onConfirmationDialogCancelHandler}>Cancel</button>
                    <button className="btn" onClick={onConfirmationDialogConfirmHandler}>Confirm</button>
                </div>
            </div>
        </div>
    )
}

// vue3-pinia/src/views/CarList/widgets/EditCarDialog/componenets/EditCarConfirmationDialog.vue
<script setup lang="ts">
import { useEditCarConfirmationDialogUI } from "@/views/CarList/widgets/EditCarDialog/store/useEditCarConfirmationDialogUI";

const editCarConfirmationDialogUI = useEditCarConfirmationDialogUI();
</script>

<template>
  <div :class="['modal', { 'modal-open': editCarConfirmationDialogUI.isOpen }]">
    <div class="modal-box relative">
      <h3 class="font-bold text-lg mb-5">Edit car</h3>
      <p class="py-4">Form contains unsaved data. Please confirm action.</p>
      <div class="modal-action">
        <button
          class="btn btn-secondary"
          @click="editCarConfirmationDialogUI.cancelClose"
        >
          Cancel
        </button>
        <button class="btn" @click="editCarConfirmationDialogUI.confirmClose">
          Confirm
        </button>
      </div>
    </div>
  </div>
</template>
