// next-beta/app/widgets/CarList/components/CarListHeader.tsx
import {CreateCarButtonWidget} from "../../CreateCarButton/CreateCarButton.widget";

export const CarListHeader = () => {
    return (
        <div className="card w-96 bg-base-100 shadow-xl">
            <div className="card-body">
                <h2 className="card-title flex justify-between">Car list <CreateCarButtonWidget/></h2>
            </div>
        </div>
    )
}

// vue3-pinia/src/views/CarList/componenents/CarListHeader.vue
<script setup lang="ts">
import CreateCarButton from "../widgets/ShowCreateCarDialogButton/ShowCreateCarDialogButton.widget.vue";
</script>

<template>
  <div class="card w-96 bg-base-100 shadow-xl">
    <div class="card-body">
      <h2 class="card-title flex justify-between">
        Car list
        <CreateCarButton />
      </h2>
    </div>
  </div>
</template>
