// next-beta/app/widgets/CreateCarDialog/components/CreateCarDialogContent.tsx
'use client'

import {useCreateCarDialogForm} from "../hooks/useCreateCarDialogForm";
import {useCreateCarMutation} from "../hooks/useCreateCarMutation";
import {useCreateCarDialogContentUI} from "../hooks/useCreateCarDialogContentUI";

const useCreateCarDialogContentState = () => {
    const {
        register,
        handleSubmit,
        formState: {errors, isDirty},
    } = useCreateCarDialogForm();

    const onSubmitHandler = useCreateCarMutation(handleSubmit, isDirty);

    const {areControlsDisabled} = useCreateCarDialogContentUI();

    return {
        register,
        errors,
        onSubmitHandler,
        areControlsDisabled,
    } as const;
}

export const CreateCarDialogContent = () => {

    const {
        errors,
        areControlsDisabled,
        onSubmitHandler,
        register
    } = useCreateCarDialogContentState();

    return (
        <>
            <form className="flex flex-col gap-y-5">
                <div className="form-control w-full">
                    <label className="label">
                        <span className="label-text">Brand</span>
                    </label>
                    <input type="text" className="input input-bordered" {...register('brand')}/>
                    {!!errors.brand && <label className="label-text text-error">{errors.brand.message}</label>}
                </div>
                <div className="form-control w-full">
                    <label className="label">
                        <span className="label-text">Model</span>
                    </label>
                    <input type="text" className="input input-bordered" {...register('model')}/>
                    {!!errors.model && <label className="label-text text-error">{errors.model.message}</label>}
                </div>
                <div className="form-control w-full">
                    <label className="label">
                        <span className="label-text">Year</span>
                    </label>
                    <input type="text" className="input input-bordered" {...register('year')}/>
                    {!!errors.year && <label className="label-text text-error">{errors.year.message}</label>}
                </div>
            </form>
            <div className="modal-action">
                <button className={areControlsDisabled ? 'btn btn-disabled' : 'btn'}
                        onClick={onSubmitHandler}>Create
                </button>
            </div>
        </>
    )
}

// vue3-pinia/src/views/CarList/widgets/CreateCarDialog/components/CreateCarDialogContent.vue
<script setup lang="ts">
import { useCreateCarDialogContentUI } from "@/views/CarList/widgets/CreateCarDialog/store/useCreateCarDialogContentUI";
import { useCreateCarDialogMutation } from "@/views/CarList/widgets/CreateCarDialog/store/useCreateCarDialogMutation";
import { useCreateCarDialogForm } from "@/views/CarList/widgets/CreateCarDialog/store/useCreateCarDialogForm";

const createCarDialogContentUI = useCreateCarDialogContentUI();
const createCarDialogMutation = useCreateCarDialogMutation();
const createCarDialogForm = useCreateCarDialogForm();
</script>

<template>
  <form class="flex flex-col gap-y-5">
    <div class="form-control w-full">
      <label class="label">
        <span class="label-text">Brand</span>
      </label>
      <input
        type="text"
        class="input input-bordered"
        v-model="createCarDialogForm.v$.brand.$model"
      />
      <template
        v-for="error of createCarDialogForm.v$.brand.$errors"
        :key="error.$uid"
      >
        <label class="label-text text-error">{{ error.$message }}</label>
      </template>
    </div>
    <div class="form-control w-full">
      <label class="label">
        <span class="label-text">Model</span>
      </label>
      <input
        type="text"
        class="input input-bordered"
        v-model="createCarDialogForm.v$.model.$model"
      />
      <template
        v-for="error of createCarDialogForm.v$.model.$errors"
        :key="error.$uid"
      >
        <label class="label-text text-error">{{ error.$message }}</label>
      </template>
    </div>
    <div class="form-control w-full">
      <label class="label">
        <span class="label-text">Year</span>
      </label>
      <input
        type="text"
        class="input input-bordered"
        v-model="createCarDialogForm.v$.year.$model"
      />
      <template
        v-for="error of createCarDialogForm.v$.year.$errors"
        :key="error.$uid"
      >
        <label class="label-text text-error">{{ error.$message }}</label>
      </template>
    </div>
  </form>
  <div class="modal-action">
    <button
      :class="[
        { 'btn-disabled': createCarDialogContentUI.areControlsDisabled },
        'btn',
      ]"
      @click="createCarDialogMutation.createCar"
    >
      Create
    </button>
  </div>
</template>
