// next-beta/app/widgets/CreateCarDialog/components/CreateCarConfirmationDialog.tsx
'use client'

import {useCreateCarConfirmationDialogUI} from "../hooks/useCreateCarConfirmationDialogUI";

export const CreateCarConfirmationDialog = () => {
    const {
        onCreateCarConfirmationDialogConfirmHandler,
        onCreateCarConfirmationDialogCancelHandler,
        isCreateCarConfirmationDialogOpen
    } = useCreateCarConfirmationDialogUI();

    if(!isCreateCarConfirmationDialogOpen) return null;

    return (
        <div className="modal modal-open">
            <div className="modal-box relative">
                <h3 className="font-bold text-lg mb-5">Edit car</h3>
                <p className="py-4">Form contains unsaved data. Please confirm action.</p>
                <div className="modal-action">
                    <button className="btn btn-secondary" onClick={onCreateCarConfirmationDialogCancelHandler}>Cancel</button>
                    <button className="btn" onClick={onCreateCarConfirmationDialogConfirmHandler}>Confirm</button>
                </div>
            </div>
        </div>
    )
}

// vue3-pinia/src/views/CarList/widgets/CreateCarDialog/components/CreateCarConfirmationDialog.vue
<script setup lang="ts">
import { useCreateCarConfirmationDialogUI } from "@/views/CarList/widgets/CreateCarDialog/store/useCreateCarConfirmationDialogUI";

const createCarConfirmationDialogUI = useCreateCarConfirmationDialogUI();
</script>

<template>
  <div
    :class="['modal', { 'modal-open': createCarConfirmationDialogUI.isOpen }]"
  >
    <div class="modal-box relative">
      <h3 class="font-bold text-lg mb-5">Create car</h3>
      <p class="py-4">Form contains unsaved data. Please confirm action.</p>
      <div class="modal-action">
        <button
          class="btn btn-secondary"
          @click="createCarConfirmationDialogUI.cancelClose"
        >
          Cancel
        </button>
        <button class="btn" @click="createCarConfirmationDialogUI.confirmClose">
          Confirm
        </button>
      </div>
    </div>
  </div>
</template>
