// vue3-pinia/src/views/CarList/widgets/EditCarDialog/componenets/EditCarDialogContent.vue
<script setup lang="ts">
import { useEditCarDialogForm } from "@/views/CarList/widgets/EditCarDialog/store/useEditCarDialogForm";
import { useEditCarDialogContentUI } from "@/views/CarList/widgets/EditCarDialog/store/useEditCarDialogContentUI";
import { useDeleteCarMutation } from "@/views/CarList/widgets/EditCarDialog/store/useDeleteCarMutation";
import { useEditCarMutation } from "@/views/CarList/widgets/EditCarDialog/store/useEditCarMutation";

const props = defineProps<{ id: number }>();
const editCarDialogForm = useEditCarDialogForm();
const editCarDialogContentUI = useEditCarDialogContentUI();
const deleteCarMutation = useDeleteCarMutation();
const editCarMutation = useEditCarMutation();
await editCarDialogForm.load(props.id);
</script>
<template>
  <form class="flex flex-col gap-y-5">
    <div class="form-control w-full">
      <label class="label">
        <span class="label-text">Brand</span>
      </label>
      <input
        type="text"
        class="input input-bordered"
        v-model="editCarDialogForm.v$.brand.$model"
      />
      <template
        v-for="error of editCarDialogForm.v$.brand.$errors"
        :key="error.$uid"
      >
        <label class="label-text text-error">{{ error.$message }}</label>
      </template>
    </div>
    <div class="form-control w-full">
      <label class="label">
        <span class="label-text">Model</span>
      </label>
      <input
        type="text"
        class="input input-bordered"
        v-model="editCarDialogForm.v$.model.$model"
      />
      <template
        v-for="error of editCarDialogForm.v$.model.$errors"
        :key="error.$uid"
      >
        <label class="label-text text-error">{{ error.$message }}</label>
      </template>
    </div>
    <div class="form-control w-full">
      <label class="label">
        <span class="label-text">Year</span>
      </label>
      <input
        type="text"
        class="input input-bordered"
        v-model="editCarDialogForm.v$.year.$model"
      />
      <template
        v-for="error of editCarDialogForm.v$.year.$errors"
        :key="error.$uid"
      >
        <label class="label-text text-error">{{ error.$message }}</label>
      </template>
    </div>
  </form>
  <div class="modal-action">
    <button
      :class="[
        { 'btn-disabled': editCarDialogContentUI.areControlsDisabled },
        'btn btn-error',
      ]"
      @click="deleteCarMutation.deleteCar"
    >
      Delete
    </button>
    <button
      :class="[
        { 'btn-disabled': editCarDialogContentUI.areControlsDisabled },
        'btn',
      ]"
      @click="editCarMutation.editCar"
    >
      Edit
    </button>
  </div>
</template>

// next-beta/widgets/EditCarDialog/components/EditCarDialogContent.tsx
'use client'
import {useEditCarDialogForm} from "../hooks/useEditCarDialogForm";
import {useEditCarMutation} from "../hooks/useEditCarMutation";
import {useDeleteCarMutation} from "../hooks/useDeleteCarMutation";
import {useEditCarDialogContentUI} from "../hooks/useEditCarDialogContentUI";

const useEditCarDialogContentState = () => {
    const {
        register,
        handleSubmit,
        formState: {errors, isDirty},
    } = useEditCarDialogForm();

    const onSubmitHandler = useEditCarMutation(handleSubmit, isDirty);
    const onDeleteHandler = useDeleteCarMutation();

    const {areControlsDisabled} = useEditCarDialogContentUI();

    return {
        register,
        errors,
        onSubmitHandler,
        onDeleteHandler,
        areControlsDisabled,
    } as const;
}

export const EditCarDialogContent = () => {

    const {
        errors,
        onDeleteHandler,
        areControlsDisabled,
        onSubmitHandler,
        register
    } = useEditCarDialogContentState();

    return (
        <>
            <form className="flex flex-col gap-y-5">
                <div className="form-control w-full">
                    <label className="label">
                        <span className="label-text">Brand</span>
                    </label>
                    <input type="text" className="input input-bordered" {...register('brand')}/>
                </div>
                <div className="form-control w-full">
                    <label className="label">
                        <span className="label-text">Model</span>
                    </label>
                    <input type="text" className="input input-bordered" {...register('model')}/>
                    {!!errors.model && <label className="label-text text-error">{errors.model.message}</label>}
                </div>
                <div className="form-control w-full">
                    <label className="label">
                        <span className="label-text">Year</span>
                    </label>
                    <input type="text" className="input input-bordered" {...register('year')}/>
                </div>
            </form>
            <div className="modal-action">
                <button className={areControlsDisabled ? 'btn btn-error btn-disabled' : 'btn btn-error'}
                        onClick={onDeleteHandler}>Delete
                </button>
                <button className={areControlsDisabled ? 'btn btn-disabled' : 'btn'}
                        onClick={onSubmitHandler}>Edit
                </button>
            </div>
        </>
    )
}
